### ISSUE TITLE
1.16.5 Arrow crashing when hitting a modded entity that might not provide model parts cleanly

### ISSUE THREAD

**Issue by Colin-J-Wood** [baguchan/PierceArrow#2]
[crash-2022-02-02_21.41.45-client.txt](https://github.com/baguchan/PierceArrow/files/7990256/crash-2022-02-02_21.41.45-client.txt)

```
Time: 2/2/22 9:41 PM
Description: Rendering entity in world

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_51] {}
	at net.minecraft.client.renderer.entity.model.EntityModel.getRandomModelPart(SourceFile:536) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:piercearrow.mixins.json:client.EntityModelMixin,pl:mixin:A}
	at baguchan.piercearrow.client.layer.LivingStuckInBodyLayer.render(LivingStuckInBodyLayer.java:36) ~[?:1.16.5-1.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at baguchan.piercearrow.client.layer.LivingStuckInBodyLayer.func_225628_a_(LivingStuckInBodyLayer.java:19) ~[?:1.16.5-1.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:204) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:obfuscate.mixins.json:client.OptifineLivingRendererMixin,pl:mixin:APP:mixins.replaymod.json:MixinRenderLivingBase,pl:mixin:APP:mixins.replaymod.json:Mixin_HideNameTags_LivingEntity,pl:mixin:APP:mixins.replaymod.json:Mixin_RenderLivingBase,pl:mixin:APP:origins.mixins.json:LivingEntityRendererMixin,pl:mixin:APP:charm.mixins.json:accessor.LivingRendererAccessor,pl:mixin:APP:brutalbosses.mixins.json:LivingRendererMixin,pl:mixin:APP:twoplayersonehorse.mixins.json:LivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:47) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:20) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}```

**Comment by Colin-J-Wood** [comment]
to reproduce, have improved mobs and quark phantoms in the nether installed, and have them attempt to shoot each other until an arrow hits

**Comment by Colin-J-Wood** [comment]
ah I see...you have deprecated 1.16.5.  well then.  just gonna remove the mod from my pack.  thanks anyway

**Comment by Dakedres** [comment]
I've encountered this error too!

**Comment by NighthowlerStudios** [comment]
This error also occured with Piglins
