### ISSUE TITLE
Crash starting minecraft caused by pierced arrow mixin 1.16.5 1.1.0

### ISSUE THREAD

**Issue by maximogta** [baguchan/PierceArrow#4]
https://pastebin.com/LRkKQubA
it loaded normally in previous version 1.0.0

 Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [piercearrow.mixins.json:client.ModelRendererMixin] from phase [DEFAULT] in config [piercearrow.mixins.json] FAILED during APPLY
[22:47:14] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[22:47:14] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[22:47:14] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[22:47:14] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 26 more
[22:47:14] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field cubes was not located in the target class net.minecraft.client.renderer.model.ModelRenderer. Using refmap piercearrow.refmap.json

**Comment by ekiplier** [comment]
Can confirm, I got this crash also:
[crash-2022-05-31_03.11.50-client.txt](https://github.com/baguchan/PierceArrow/files/8801512/crash-2022-05-31_03.11.50-client.txt)
